export const EMAIL_REGEX = /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g;

export const PHONE_PATTERNS = [
  /(?:\+?1[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}/g,
  /\b\d{3}\.\d{3}\.\d{4}\b/g,
  /\b\d{3}\s\d{3}\s\d{4}\b/g,
  /\b\d{3}[-.\s]?\d{3}[-.\s]?\d{4}(?:\s*(?:x|ext\.?|extension)\s*\d+)?\b/gi,
];

export const TRADE_MAPPINGS: { keywords: string[]; trade: string }[] = [
  {
    keywords: [
      'electrical',
      'electric',
      'lighting',
      'conduit',
      'panel',
      'wiring',
      'musco',
      'light pole',
    ],
    trade: 'Electrical',
  },
  {
    keywords: [
      'plumbing',
      'piping',
      'fixtures',
      'drain',
      'water line',
      'sanitary',
      'lavatory',
      'water closet',
      'domestic water',
    ],
    trade: 'Plumbing',
  },
  {
    keywords: ['concrete', 'foundation', 'slab', 'footing', 'curb', 'flatwork', 'rebar', 'pour'],
    trade: 'Concrete',
  },
  {
    keywords: [
      'low voltage',
      'data cabling',
      'cat 6',
      'cat6',
      'network',
      'structured cabling',
      'data drops',
      'patch panel',
      'telecommunications',
    ],
    trade: 'Low Voltage / Cabling',
  },
  {
    keywords: [
      'sitework',
      'excavation',
      'grading',
      'earthwork',
      'civil',
      'clearing',
      'grubbing',
      'mass excavation',
    ],
    trade: 'Sitework / Civil',
  },
  {
    keywords: [
      'hvac',
      'mechanical',
      'heating',
      'cooling',
      'ventilation',
      'air conditioning',
      'ductwork',
    ],
    trade: 'HVAC / Mechanical',
  },
  {
    keywords: ['roofing', 'roof', 'shingle', 'membrane'],
    trade: 'Roofing',
  },
  {
    keywords: ['demolition', 'demo', 'abatement'],
    trade: 'Demolition',
  },
  {
    keywords: ['paving', 'asphalt', 'striping'],
    trade: 'Paving',
  },
  {
    keywords: ['landscaping', 'irrigation', 'planting', 'sodding'],
    trade: 'Landscaping',
  },
  {
    keywords: ['fire protection', 'sprinkler', 'fire alarm'],
    trade: 'Fire Protection',
  },
  {
    keywords: ['steel', 'structural steel', 'metal framing'],
    trade: 'Structural Steel',
  },
  {
    keywords: ['drywall', 'framing', 'carpentry'],
    trade: 'Carpentry / Drywall',
  },
];

export const COMPANY_SUFFIXES = [
  'inc\\.?',
  'llc',
  'corp\\.?',
  'corporation',
  'company',
  'co\\.?',
  'ltd\\.?',
  'limited',
  'contractors',
  'contracting',
  'construction',
  'builders',
  'services',
  'enterprises',
  'group',
  'solutions',
  'associates',
  'communications',
  'mechanical',
  'electric',
  'plumbing',
  'concrete',
];

export const COMPANY_LINE_BLACKLIST = [
  'contact',
  'project',
  'description',
  'qty',
  'quantity',
  'total',
  'scope',
  'scope of work',
  'work',
  'package',
  'estimated quantity',
  'proposal',
  'bid form',
  'base bid',
  'alternate',
  'addendum',
  'schedule',
  'submittal',
  'invoice',
  'purchase order',
  'po box',
  'remit',
  'bill to',
  'ship to',
  'one per',
  'two in',
  'each',
  'per office',
  'per printer',
  'includes',
  'drawings',
  'by',
  'engineering',
  'corp',
  'safe',
  'provide',
  'furnish',
];

export const ADDRESS_HINTS = [
  'st',
  'street',
  'ave',
  'avenue',
  'rd',
  'road',
  'blvd',
  'boulevard',
  'ln',
  'lane',
  'dr',
  'drive',
  'ct',
  'court',
  'pkwy',
  'parkway',
  'suite',
  'ste',
  'unit',
  'highway',
  'hwy',
];
